<?php
/**
 * @file
 * Installation hooks for Open Restaurant Pages.
 */

use Drupal\node\Entity\Node;
use Drupal\menu_link_content\Entity\MenuLinkContent;

/**
 * Implements hook_install().
 */
function openrestaurant_pages_install() {
  // Set front page to node with id 1.
  // Created via theme demo_content.
  \Drupal::configFactory()->getEditable('system.site')->set('page.front', '/node/1')->save(TRUE);
}
